//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locima.SlidingBlock.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Locima.SlidingBlock.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutMenuOption {
            get {
                return ResourceManager.GetString("AboutMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author would like to acknowledge the following people and organisations who provided either inspiration or some great tips and code snippets on the Internet that were used within this app..
        /// </summary>
        public static string AcknowledgementsLeader {
            get {
                return ResourceManager.GetString("AcknowledgementsLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add player.
        /// </summary>
        public static string AddNewPlayerTitle {
            get {
                return ResourceManager.GetString("AddNewPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add player.
        /// </summary>
        public static string AddPlayer {
            get {
                return ResourceManager.GetString("AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add level.
        /// </summary>
        public static string AppendLevelButton {
            get {
                return ResourceManager.GetString("AppendLevelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLIDING BLOCK.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to author.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autosolve.
        /// </summary>
        public static string Autosolve {
            get {
                return ResourceManager.GetString("Autosolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue game.
        /// </summary>
        public static string ContinueGame {
            get {
                return ResourceManager.GetString("ContinueGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue the current game.
        /// </summary>
        public static string ContinueGameDescription {
            get {
                return ResourceManager.GetString("ContinueGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string CreateCustomGame {
            get {
                return ResourceManager.GetString("CreateCustomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create level.
        /// </summary>
        public static string CreateLevel {
            get {
                return ResourceManager.GetString("CreateLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit game template.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new custom game.
        /// </summary>
        public static string CustomDescription {
            get {
                return ResourceManager.GetString("CustomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string CustomGameContextMenuDelete {
            get {
                return ResourceManager.GetString("CustomGameContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Game.
        /// </summary>
        public static string DefaultGameDefinitionTitle {
            get {
                return ResourceManager.GetString("DefaultGameDefinitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string DefaultPlayerName {
            get {
                return ResourceManager.GetString("DefaultPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} save game(s).  Click OK to delete all these games as well as the player record, or cancel to abort the operation.
        /// </summary>
        public static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete player.
        /// </summary>
        public static string DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit level.
        /// </summary>
        public static string EditLevel {
            get {
                return ResourceManager.GetString("EditLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit player.
        /// </summary>
        public static string EditPlayerTitle {
            get {
                return ResourceManager.GetString("EditPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!  You&apos;ve completed the single player game in a total of {0} using {1} moves, which places you {2} on the high score table.  Times for each level are shown below..
        /// </summary>
        public static string EndGameMessage {
            get {
                return ResourceManager.GetString("EndGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game over.
        /// </summary>
        public static string EndGameTitle {
            get {
                return ResourceManager.GetString("EndGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a game using a {0} x {1} grid.
        /// </summary>
        public static string GameDescription {
            get {
                return ResourceManager.GetString("GameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game name.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level {0}.
        /// </summary>
        public static string GamePageTitle {
            get {
                return ResourceManager.GetString("GamePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high scores.
        /// </summary>
        public static string GoToHighscores {
            get {
                return ResourceManager.GetString("GoToHighscores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high scores.
        /// </summary>
        public static string HighscorePageTitle {
            get {
                return ResourceManager.GetString("HighscorePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} moves in {1}.
        /// </summary>
        public static string HighscoreStats {
            get {
                return ResourceManager.GetString("HighscoreStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Description.
        /// </summary>
        public static string ImageTextLabel {
            get {
                return ResourceManager.GetString("ImageTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Title.
        /// </summary>
        public static string ImageTitleLabel {
            get {
                return ResourceManager.GetString("ImageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL COMPLETE.
        /// </summary>
        public static string LevelFinishedCaption {
            get {
                return ResourceManager.GetString("LevelFinishedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have completed level {0} in a total of {1} using {2} {3}..
        /// </summary>
        public static string LevelFinishedMessage {
            get {
                return ResourceManager.GetString("LevelFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level:.
        /// </summary>
        public static string LevelLabel {
            get {
                return ResourceManager.GetString("LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to levels.
        /// </summary>
        public static string LevelList {
            get {
                return ResourceManager.GetString("LevelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Uri.
        /// </summary>
        public static string LicenceUriLabel {
            get {
                return ResourceManager.GetString("LicenceUriLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicenseLabel {
            get {
                return ResourceManager.GetString("LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran this application. Would you like to send an email to report it?.
        /// </summary>
        public static string LittleWatson_Message {
            get {
                return ResourceManager.GetString("LittleWatson_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Report.
        /// </summary>
        public static string LittleWatson_Title {
            get {
                return ResourceManager.GetString("LittleWatson_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load game.
        /// </summary>
        public static string LoadGame {
            get {
                return ResourceManager.GetString("LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a saved game.
        /// </summary>
        public static string LoadGameDescription {
            get {
                return ResourceManager.GetString("LoadGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Pictures.
        /// </summary>
        public static string LocalPictures {
            get {
                return ResourceManager.GetString("LocalPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a picture from your phone.
        /// </summary>
        public static string LocalPicturesDescription {
            get {
                return ResourceManager.GetString("LocalPicturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moves in.
        /// </summary>
        public static string MovesInLabel {
            get {
                return ResourceManager.GetString("MovesInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moves:.
        /// </summary>
        public static string MovesLabel {
            get {
                return ResourceManager.GetString("MovesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start new game.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a new game from scratch.
        /// </summary>
        public static string NewGameDescription {
            get {
                return ResourceManager.GetString("NewGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no high scores yet!.
        /// </summary>
        public static string NoHighscoresFound {
            get {
                return ResourceManager.GetString("NoHighscoresFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no saved games found!.
        /// </summary>
        public static string NoSavedGamesFound {
            get {
                return ResourceManager.GetString("NoSavedGamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        public static string PausedMessage {
            get {
                return ResourceManager.GetString("PausedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string PlayerContextMenuDelete {
            get {
                return ResourceManager.GetString("PlayerContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string PlayerContextMenuEdit {
            get {
                return ResourceManager.GetString("PlayerContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level {0}.
        /// </summary>
        public static string SaveGameLevelTitle {
            get {
                return ResourceManager.GetString("SaveGameLevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string SaveGameSelectorDeleteGame {
            get {
                return ResourceManager.GetString("SaveGameSelectorDeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select save game.
        /// </summary>
        public static string SaveGameSelectorPageTitle {
            get {
                return ResourceManager.GetString("SaveGameSelectorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SavePlayer {
            get {
                return ResourceManager.GetString("SavePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identity.
        /// </summary>
        public static string ScramblerType_Identity {
            get {
                return ResourceManager.GetString("ScramblerType_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one move to finish.
        /// </summary>
        public static string ScramblerType_OneMoveToFinish {
            get {
                return ResourceManager.GetString("ScramblerType_OneMoveToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random.
        /// </summary>
        public static string ScramblerType_Random {
            get {
                return ResourceManager.GetString("ScramblerType_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flip along y-axis.
        /// </summary>
        public static string ScramblerType_XFlip {
            get {
                return ResourceManager.GetString("ScramblerType_XFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flip along both axes.
        /// </summary>
        public static string ScramblerType_XYFlip {
            get {
                return ResourceManager.GetString("ScramblerType_XYFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flip along x-axis.
        /// </summary>
        public static string ScramblerType_YFlip {
            get {
                return ResourceManager.GetString("ScramblerType_YFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select game.
        /// </summary>
        public static string SelectCustomGamePageName {
            get {
                return ResourceManager.GetString("SelectCustomGamePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select image.
        /// </summary>
        public static string SelectImageButton {
            get {
                return ResourceManager.GetString("SelectImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select license.
        /// </summary>
        public static string SelectLicense {
            get {
                return ResourceManager.GetString("SelectLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select player.
        /// </summary>
        public static string SelectPlayer {
            get {
                return ResourceManager.GetString("SelectPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsMenuOption {
            get {
                return ResourceManager.GetString("SettingsMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string SinglePlayerGameTitle {
            get {
                return ResourceManager.GetString("SinglePlayerGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single player game.
        /// </summary>
        public static string SinglePlayerTitle {
            get {
                return ResourceManager.GetString("SinglePlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time:.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name.
        /// </summary>
        public static string UnnamedPlayer {
            get {
                return ResourceManager.GetString("UnnamedPlayer", resourceCulture);
            }
        }
    }
}
